src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
  path('', include('yfcases.urls')),
  path('admin/', admin.site.urls),
  path('users/', include('users.urls')),
	path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yfcases/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from wkhtmltopdf.views import PDFTemplateView

app_name='yfcase'

urlpatterns = [
  path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
  path('',views.YfcaseListView.as_view(),name="home" ),
  path('yfcase/<int:pk>/',views.YfcaseDetailView.as_view(),name="yfcase_detail"),
  path('yfcase/new/',views.YfcaseCreateView.as_view(),name="yfcase_new"),
  path('yfcase/<int:pk>/edit/',views.YfcaseUpdateView.as_view(),name="yfcase_edit"),
  path('yfcase/<int:pk>/delete/',views.YfcaseDeleteView.as_view(),name="yfcase_delete"),
  path('land/new/',views.LandCreateView.as_view(),name="land_new"),
  path('land/<int:pk>/edit/',views.LandUpdateView.as_view(),name="land_edit"),
  path('land/<int:pk>/delete/',views.LandDeleteView.as_view(),name="land_delete"),
  path('build/new/',views.BuildCreateView.as_view(),name="build_new"),
  path('build/<int:pk>/edit/',views.BuildUpdateView.as_view(),name="build_edit"),
  path('build/<int:pk>/delete/',views.BuildDeleteView.as_view(),name="build_delete"),
  path('auction/new/',views.AuctionCreateView.as_view(),name="auction_new"),
  path('auction/<int:pk>/edit/',views.AuctionUpdateView.as_view(),name="auction_edit"),
  path('survey/new/',views.SurveyCreateView.as_view(),name="survey_new" ),
  path('survey/<int:pk>/edit/',views.SurveyUpdateView.as_view(),name="survey_edit" ),
  path('clicklist/new/',views.ClickListCreateView.as_view(),name="clicklist_new" ),
  path('clicklist/<int:pk>/edit/',views.ClickListUpdateView.as_view(),name="clicklist_edit"),
  path('objectbuild/new/',views.ObjectBuildCreateView.as_view(),name="objectbuild_new" ),
  path('objectbuild/<int:pk>/edit/',views.ObjectBuildUpdateView.as_view(),name="objectbuild_edit"),
  path('objectbuild/<int:pk>/delete/',views.ObjectBuildDeleteView.as_view(),name="objectbuild_delete"),
  path('scorea/<int:pk>/edit/',views.ScoreAUpdateView.as_view(),name="score_a_edit"),
  path('scoreb/<int:pk>/edit/',views.ScoreBUpdateView.as_view(),name="score_b_edit"),
  path('scorec/<int:pk>/edit/',views.ScoreCUpdateView.as_view(),name="score_c_edit"),
  path('scorea/<int:pk>/delete/',views.ScoreADeleteView.as_view(),name="score_a_delete"),
  path('scoreb/<int:pk>/delete/',views.ScoreBDeleteView.as_view(),name="score_b_delete"),
  path('scorec/<int:pk>/delete/',views.ScoreCDeleteView.as_view(),name="score_c_delete"),
  path('regionalhead/new/',views.RegionalHeadCreateView.as_view(),name="regionalhead_new" ),
  path('regionalhead/<int:pk>/edit/',views.RegionalHeadUpdateView.as_view(),name="regionalhead_edit" ),
  path('regionalhead/<int:pk>/delete/',views.RegionalHeadDeleteView.as_view(),name="regionalhead_delete" ),
  path('subsigntruea/new/',views.SubSigntrueACreateView.as_view(),name="subsigntruea_new" ),
  path('subsigntruea/<int:pk>/edit/',views.SubSigntrueAUpdateView.as_view(),name="subsigntruea_edit" ),
  path('subsigntruea/<int:pk>/delete/',views.SubSigntrueADeleteView.as_view(),name="subsigntruea_delete" ),
  path('subsigntrueb/new/',views.SubSigntrueBCreateView.as_view(),name="subsigntrueb_new" ),
  path('subsigntrueb/<int:pk>/edit/',views.SubSigntrueBUpdateView.as_view(),name="subsigntrueb_edit" ),
  path('subsigntrueb/<int:pk>/delete/',views.SubSigntrueBDeleteView.as_view(),name="subsigntrueb_delete" ),
  path('ajax/load-townships/', views.load_townships, name='ajax_load_townships'),
  
  path('deedtax/<int:pk>/edit/', views.DeedtaxUpdateView.as_view(), name='deedtax_edit'),
  path('realestateregistration/<int:pk>/edit/', views.RealestateregistrationUpdateView.as_view(), name='realestateregistration_edit'),
  path('complaint/<int:pk>/edit/', views.ComplaintUpdateView.as_view(), name='complaint_edit'),
  path('letter/<int:pk>/edit/', views.LetterUpdateView.as_view(), name='letter_edit'),
  path('commonpropertydivision/<int:pk>/edit/', views.CommonpropertydivisionUpdateView.as_view(), name='commonpropertydivision_edit'),
  
  path('yfratingscalePDFView/<int:pk>/', views.yfratingscalePDFView.as_view(),name="yfratingscalePDF_View"),
  path('deedtaxPDFView/<int:pk>/', views.deedtaxPDFView.as_view(),name="deedtaxPDF_View"),
  path('realestateregistrationPDFView/<int:pk>/', views.realestateregistrationPDFView.as_view(),name="realestateregistrationPDF_View"),
  path('complaintPDFView/<int:pk>/', views.complaintPDFView.as_view(),name="complaintPDF_View"),
  path('letterPDFView/<int:pk>/', views.letterPDFView.as_view(),name="letterPDF_View"),
  path('commonpropertydivisionPDFView/<int:pk>/', views.commonpropertydivisionPDFView.as_view(),name="commonpropertydivisionPDF_View"),
]

templates/finaldecision/regional_head_delete.html
<form action="{% url 'yfcase:regionalhead_delete' yfcase.id %}" method="post">{% csrf_token %}

  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
       {{ form }}
      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-success col-md-3" type="submit" value="Save Change" />
      </div>

    </div>
  </div>
</form>

templates/finaldecision/regional_head_edit.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:regionalhead_edit' yfcase.id %}" method="post">{% csrf_token %}

  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!-- body -->
      <div class="modal-body">
        
        {{ form.regionalHead|attr:"type:hidden" }}
        {{ form.regionalHeadWorkArea|attr:"type:hidden" }}
            
        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.finalDecision.label }}</label>
            {{ form.finalDecision|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.regionalHeadDate.label }}</label>
            {{ form.regionalHeadDate|add_class:"form-control fieldcolor datepicker pt-0" }}
            <small style="color:blue;">*若此欄位為空值，則日期以"五天後"的日期為主</small>
          </div>
        </div>

       {{ request.user.userFullName|json_script:"author_fullname" }} 
       {{ request.user.userWorkArea|json_script:"author_workarea" }} 

      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary col" data-dismiss="modal">關閉</button>
        <input class="btn btn-primary col-md-3" type="submit" onclick="post_regional_head_submit()" value="更新" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
 $(function() {
    $( ".datepicker" ).datepicker({
      dateFormat: "yy-mm-dd",
      minDate: '+5d'
    });
    // document.getElementById("id_regionalHead").value = request.user;
  });
  
  function post_regional_head_submit() {
      var Today = new Date();
      var addToday = Today.getFullYear()+ "-" + ("0" + (Today.getMonth() + 1)).slice(-2) + "-" + ("0" + (Today.getDate()+5)).slice(-2)
      const author_fullname = JSON.parse(document.getElementById('author_fullname').textContent);
      document.getElementById("id_regionalHead").value = author_fullname;
      const author_workarea = JSON.parse(document.getElementById('author_workarea').textContent);
      document.getElementById("id_regionalHeadWorkArea").value = author_workarea;
      if (document.getElementById("id_regionalHeadDate").value == "") {
        document.getElementById("id_regionalHeadDate").value = addToday;
      } else {
        document.getElementById("id_regionalHeadDate").value = document.getElementById("id_regionalHeadDate").value;
      }
  }
</script>
{% endblock javascript %}

templates/finaldecision/regional_head_new.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:regionalhead_new' %}" method="post">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
     
      <!-- body -->
      <div class="modal-body">
        
        {{ form.regionalHead|attr:"type:hidden" }}
        {{ form.regionalHeadWorkArea|attr:"type:hidden" }}
        
            
        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.finalDecision.label }}</label>
            {{ form.finalDecision|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.regionalHeadDate.label }}</label>
            {{ form.regionalHeadDate|add_class:"form-control fieldcolor datepicker pt-0" }}
            <small style="color:blue;">*若此欄位為空值，則日期以"五天後"的日期為主</small>
          </div>
        </div>

        {{ request.user.userFullName|json_script:"author_fullname" }} 
        {{ request.user.userWorkArea|json_script:"author_workarea" }} 

      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-success col-md-3" type="submit" onclick="get_regional_yfcase()" value="Save Change" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  $(function() {
    $(".datepicker").datepicker({
      dateFormat: "yy-mm-dd",
      minDate: '+5d'
    });
  });

  function get_regional_yfcase() {
    var url = (window.location.pathname).replace("/yfcase/","").replace("/","");
    var Today = new Date();
    var addToday = Today.getFullYear()+ "-" + ("0" + (Today.getMonth() + 1)).slice(-2) + "-" + ("0" + (Today.getDate()+5)).slice(-2)
    const author_fullname = JSON.parse(document.getElementById('author_fullname').textContent);
    document.getElementById("id_regionalHead").value = author_fullname;
    const author_workarea = JSON.parse(document.getElementById('author_workarea').textContent);
    document.getElementById("id_regionalHeadWorkArea").value = author_workarea;
    if (document.getElementById("id_regionalHeadDate").value == "") {
      document.getElementById("id_regionalHeadDate").value = addToday;
    } else {
      document.getElementById("id_regionalHeadDate").value = document.getElementById("id_regionalHeadDate").value;
    }
    document.getElementById("id_yfcase").value = url;
  }
  
</script>
{% endblock %}

templates/finaldecision/sub_signtrue_A_delete.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:subsigntruea_delete' yfcase.id %}" method="post">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">刪除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
        <p>你確定要刪除 "{{finaldecision.subSigntrueA}}" ?</p>
        {{ form.yfcase|attr:"type:hidden" }}
        {{ form.subSigntrueA|attr:"type:hidden" }}
        {{ form.subSigntrueDateA|attr:"type:hidden" }}
      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
        <input class="btn btn-success col-md-3" type="submit" onclick="set_subsigntruea_empty()" value="刪除" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  function set_subsigntruea_empty() {

     document.getElementById("id_subSigntrueA").value = "";
     document.getElementById("id_subSigntrueDateA").value = "";

  }
</script>
{% endblock javascript %}

templates/finaldecision/sub_signtrue_A_edit.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:subsigntruea_edit' yfcase.id %}" method="post">{% csrf_token %}

  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">

        {{ form.subSigntrueA|attr:"type:hidden" }}
        {{ form.subSigntrueWorkAreaA|attr:"type:hidden" }}

        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.subSigntrueDateA.label }}</label>
            {{ form.subSigntrueDateA|add_class:"form-control fieldcolor pt-0" }}
            <small style="color:blue;">*若此欄位為空值，則日期以當天的日期為主</small>
          </div>
        </div>
        {{ request.user.userFullName|json_script:"author_fullname" }} 
        {{ request.user.userWorkArea|json_script:"author_workarea" }} 
      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary col" data-dismiss="modal">關閉</button>
        <input class="btn btn-primary col-md-3" type="submit" onclick="post_sub_signtrue_a_submit()" value="更新" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
 $(function() {
    $( ".datepicker" ).datepicker({
      dateFormat: "yy-mm-dd",
      minDate: '+0d'
    });
  });

  function post_sub_signtrue_a_submit() {
    var Today = new Date();
    var addToday = Today.getFullYear()+ "-" + ("0" + (Today.getMonth() + 1)).slice(-2) + "-" + ("0" + Today.getDate()).slice(-2)
    const author_fullname = JSON.parse(document.getElementById('author_fullname').textContent);
    document.getElementById("id_subSigntrueA").value = author_fullname;
    const author_workarea = JSON.parse(document.getElementById('author_workarea').textContent);
    document.getElementById("id_subSigntrueWorkAreaA").value = author_workarea;
    if (document.getElementById("id_subSigntrueDateA").value == "") {
      document.getElementById("id_subSigntrueDateA").value = addToday;
    } else {
      document.getElementById("id_subSigntrueDateA").value = document.getElementById("id_subSigntrueDateA").value;
    }
  }
</script>
{% endblock javascript %}

templates/finaldecision/sub_signtrue_A_new.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:subsigntruea_new' %}" method="post">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">

        {{ form.subSigntrueA|attr:"type:hidden" }}
        {{ form.subSigntrueWorkAreaA|attr:"type:hidden" }}

        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.subSigntrueA.label }}</label>
            {{ form.subSigntrueA|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.subSigntrueDateA.label }}</label>
            {{ form.subSigntrueDateA|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

      </div>
      {{ request.user.userFullName|json_script:"author_fullname" }} 
      {{ request.user.userWorkArea|json_script:"author_workarea" }} 
      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-success col-md-3" type="submit" onclick="get_signtruea_yfcase()" value="Save Change" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
 $(function() {
    $( ".datepicker" ).datepicker({
      dateFormat: "yy-mm-dd"
    });
  });
  function get_signtruea_yfcase() {
    var url = (window.location.pathname).replace("/yfcase/","").replace("/",""); 
    var Today = new Date();
    var addToday = Today.getFullYear()+ "-" + ("0" + (Today.getMonth() + 1)).slice(-2) + "-" + ("0" + Today.getDate()).slice(-2)
    const author_fullname = JSON.parse(document.getElementById('author_fullname').textContent);
    document.getElementById("id_subSigntrueA").value = author_fullname;
    const author_workarea = JSON.parse(document.getElementById('author_workarea').textContent);
    document.getElementById("id_subSigntrueWorkAreaA").value = author_workarea;
    if (document.getElementById("id_subSigntrueDateA").value == "") {
      document.getElementById("id_subSigntrueDateA").value = addToday;
    } else {
      document.getElementById("id_subSigntrueDateA").value = document.getElementById("id_subSigntrueDateA").value;
    }
    document.getElementById("id_yfcase").value = url;
  }
</script>
{% endblock javascript %}

templates/finaldecision/sub_signtrue_B_delete.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:subsigntrueb_delete' yfcase.id %}" method="post">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">刪除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
        <p>你確定要刪除 "{{finaldecision.subSigntrueB}}" ?</p>
        {{ form.yfcase|attr:"type:hidden" }}
        {{ form.subSigntrueB|attr:"type:hidden" }}
        {{ form.subSigntrueDateB|attr:"type:hidden" }}
      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
        <input class="btn btn-success col-md-3" type="submit" onclick="set_subsigntrueb_empty()" value="刪除" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  function set_subsigntrueb_empty() {

     document.getElementById("id_subSigntrueB").value = "";
     document.getElementById("id_subSigntrueDateB").value = "";

  }
</script>
{% endblock javascript %}

templates/finaldecision/sub_signtrue_B_edit.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:subsigntrueb_edit' yfcase.id %}" method="post">{% csrf_token %}

  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">

        {{ form.subSigntrueB|attr:"type:hidden" }}
        {{ form.subSigntrueWorkAreaB|attr:"type:hidden" }}

        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.subSigntrueDateB.label }}</label>
            {{ form.subSigntrueDateB|add_class:"form-control fieldcolor pt-0" }}
            <small style="color:blue;">*若此欄位為空值，則日期以當天的日期為主</small>
          </div>
        </div>
        {{ request.user.userFullName|json_script:"author_fullname" }} 
        {{ request.user.userWorkArea|json_script:"author_workarea" }}  
      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary col" data-dismiss="modal">關閉</button>
        <input class="btn btn-primary col-md-3" type="submit" onclick="post_sub_signtrue_b_submit()" value="更新" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
 $(function() {
    $( ".datepicker" ).datepicker({
      dateFormat: "yy-mm-dd",
      minDate: '+0d'
    });
  });

  function post_sub_signtrue_b_submit() {
    var Today = new Date();
    var addToday = Today.getFullYear()+ "-" + ("0" + (Today.getMonth() + 1)).slice(-2) + "-" + ("0" + Today.getDate()).slice(-2)
    const author_fullname = JSON.parse(document.getElementById('author_fullname').textContent);
    document.getElementById("id_subSigntrueB").value = author_fullname;
    const author_workarea = JSON.parse(document.getElementById('author_workarea').textContent);
    document.getElementById("id_subSigntrueWorkAreaB").value = author_workarea;
    if (document.getElementById("id_subSigntrueDateB").value == "") {
      document.getElementById("id_subSigntrueDateB").value = addToday;
    } else {
      document.getElementById("id_subSigntrueDateB").value = document.getElementById("id_subSigntrueDateB").value;
    }
  }
</script>
{% endblock javascript %}

templates/finaldecision/sub_signtrue_B_new.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:subsigntrueb_new' %}" method="post">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">

        {{ form.subSigntrueB|attr:"type:hidden" }}
        {{ form.subSigntrueWorkAreaB|attr:"type:hidden" }}

        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.subSigntrueB.label }}</label>
            {{ form.subSigntrueB|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col">
            <label>{{ form.subSigntrueDateB.label }}</label>
            {{ form.subSigntrueDateB|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

      </div>
      {{ request.user.userFullName|json_script:"author_fullname" }} 
      {{ request.user.userWorkArea|json_script:"author_workarea" }} 
      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input class="btn btn-success col-md-3" type="submit" onclick="get_signtrueb_yfcase()" value="Save Change" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
 $(function() {
    $( ".datepicker" ).datepicker({
      dateFormat: "yy-mm-dd"
    });
  });
  function get_signtrueb_yfcase() {
    var url = (window.location.pathname).replace("/yfcase/","").replace("/",""); 
    document.getElementById("id_yfcase").value = url;
    var Today = new Date();
    var addToday = Today.getFullYear()+ "-" + ("0" + (Today.getMonth() + 1)).slice(-2) + "-" + ("0" + Today.getDate()).slice(-2)
    const author_fullname = JSON.parse(document.getElementById('author_fullname').textContent);
    document.getElementById("id_subSigntrueB").value = author_fullname;
    const author_workarea = JSON.parse(document.getElementById('author_workarea').textContent);
    document.getElementById("id_subSigntrueWorkAreaB").value = author_workarea;
    if (document.getElementById("id_subSigntrueDateB").value == "") {
      document.getElementById("id_subSigntrueDateB").value = addToday;
    } else {
      document.getElementById("id_subSigntrueDateB").value = document.getElementById("id_subSigntrueDateB").value;
    }
  }
</script>
{% endblock javascript %}