src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
  path('', include('yfcases.urls')),
  path('admin/', admin.site.urls),
  path('users/', include('users.urls')),
	path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yfcases/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from wkhtmltopdf.views import PDFTemplateView

app_name='yfcase'

urlpatterns = [
  path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
  path('',views.YfcaseListView.as_view(),name="home" ),
  path('yfcase/<int:pk>/',views.YfcaseDetailView.as_view(),name="yfcase_detail"),
  path('yfcase/new/',views.YfcaseCreateView.as_view(),name="yfcase_new"),
  path('yfcase/<int:pk>/edit/',views.YfcaseUpdateView.as_view(),name="yfcase_edit"),
  path('yfcase/<int:pk>/delete/',views.YfcaseDeleteView.as_view(),name="yfcase_delete"),
  path('land/new/',views.LandCreateView.as_view(),name="land_new"),
  path('land/<int:pk>/edit/',views.LandUpdateView.as_view(),name="land_edit"),
  path('land/<int:pk>/delete/',views.LandDeleteView.as_view(),name="land_delete"),
  path('build/new/',views.BuildCreateView.as_view(),name="build_new"),
  path('build/<int:pk>/edit/',views.BuildUpdateView.as_view(),name="build_edit"),
  path('build/<int:pk>/delete/',views.BuildDeleteView.as_view(),name="build_delete"),
  path('auction/new/',views.AuctionCreateView.as_view(),name="auction_new"),
  path('auction/<int:pk>/edit/',views.AuctionUpdateView.as_view(),name="auction_edit"),
  path('survey/new/',views.SurveyCreateView.as_view(),name="survey_new" ),
  path('survey/<int:pk>/edit/',views.SurveyUpdateView.as_view(),name="survey_edit" ),
  path('clicklist/new/',views.ClickListCreateView.as_view(),name="clicklist_new" ),
  path('clicklist/<int:pk>/edit/',views.ClickListUpdateView.as_view(),name="clicklist_edit"),
  path('objectbuild/new/',views.ObjectBuildCreateView.as_view(),name="objectbuild_new" ),
  path('objectbuild/<int:pk>/edit/',views.ObjectBuildUpdateView.as_view(),name="objectbuild_edit"),
  path('objectbuild/<int:pk>/delete/',views.ObjectBuildDeleteView.as_view(),name="objectbuild_delete"),
  path('scorea/<int:pk>/edit/',views.ScoreAUpdateView.as_view(),name="score_a_edit"),
  path('scoreb/<int:pk>/edit/',views.ScoreBUpdateView.as_view(),name="score_b_edit"),
  path('scorec/<int:pk>/edit/',views.ScoreCUpdateView.as_view(),name="score_c_edit"),
  path('scorea/<int:pk>/delete/',views.ScoreADeleteView.as_view(),name="score_a_delete"),
  path('scoreb/<int:pk>/delete/',views.ScoreBDeleteView.as_view(),name="score_b_delete"),
  path('scorec/<int:pk>/delete/',views.ScoreCDeleteView.as_view(),name="score_c_delete"),
  path('regionalhead/new/',views.RegionalHeadCreateView.as_view(),name="regionalhead_new" ),
  path('regionalhead/<int:pk>/edit/',views.RegionalHeadUpdateView.as_view(),name="regionalhead_edit" ),
  path('regionalhead/<int:pk>/delete/',views.RegionalHeadDeleteView.as_view(),name="regionalhead_delete" ),
  path('subsigntruea/new/',views.SubSigntrueACreateView.as_view(),name="subsigntruea_new" ),
  path('subsigntruea/<int:pk>/edit/',views.SubSigntrueAUpdateView.as_view(),name="subsigntruea_edit" ),
  path('subsigntruea/<int:pk>/delete/',views.SubSigntrueADeleteView.as_view(),name="subsigntruea_delete" ),
  path('subsigntrueb/new/',views.SubSigntrueBCreateView.as_view(),name="subsigntrueb_new" ),
  path('subsigntrueb/<int:pk>/edit/',views.SubSigntrueBUpdateView.as_view(),name="subsigntrueb_edit" ),
  path('subsigntrueb/<int:pk>/delete/',views.SubSigntrueBDeleteView.as_view(),name="subsigntrueb_delete" ),
  path('ajax/load-townships/', views.load_townships, name='ajax_load_townships'),
  
  path('deedtax/<int:pk>/edit/', views.DeedtaxUpdateView.as_view(), name='deedtax_edit'),
  path('realestateregistration/<int:pk>/edit/', views.RealestateregistrationUpdateView.as_view(), name='realestateregistration_edit'),
  path('complaint/<int:pk>/edit/', views.ComplaintUpdateView.as_view(), name='complaint_edit'),
  path('letter/<int:pk>/edit/', views.LetterUpdateView.as_view(), name='letter_edit'),
  path('commonpropertydivision/<int:pk>/edit/', views.CommonpropertydivisionUpdateView.as_view(), name='commonpropertydivision_edit'),
  
  path('yfratingscalePDFView/<int:pk>/', views.yfratingscalePDFView.as_view(),name="yfratingscalePDF_View"),
  path('deedtaxPDFView/<int:pk>/', views.deedtaxPDFView.as_view(),name="deedtaxPDF_View"),
  path('realestateregistrationPDFView/<int:pk>/', views.realestateregistrationPDFView.as_view(),name="realestateregistrationPDF_View"),
  path('complaintPDFView/<int:pk>/', views.complaintPDFView.as_view(),name="complaintPDF_View"),
  path('letterPDFView/<int:pk>/', views.letterPDFView.as_view(),name="letterPDF_View"),
  path('commonpropertydivisionPDFView/<int:pk>/', views.commonpropertydivisionPDFView.as_view(),name="commonpropertydivisionPDF_View"),
]

templates/yfcase/partials/baseData.html
<!--基本資料-->
<table class="yfratingscalePDFBaseData">
  <tr>
    <th style="width:10%;">案號</th>
    <td style="width:35%;">{{object.yfcaseCaseNumber|default_if_none:"" }}</td>
    <th style="width:10%;">債務人</th>
    <td style="width:15%;">{{ object.yfcaseDebtor|default_if_none:"" }}</td>
    <th style="width:10%;">債權人</th>
    <td>
      {% if object.yfcaseCreditor == None %}
        {{ object.yfcaseCompany }}
      {% else %}
        {{ object.yfcaseCreditor|default_if_none:"" }}
      {% endif %}
  </tr>
  <tr>
    <th>住址</th>
    <td colspan="5">
      {{object.yfcaseCity|default_if_none:""}}{{object.yfcaseTownship|default_if_none:""}}{{object.yfcaseVillage|default_if_none:""}}{{object.yfcaseNeighbor|default_if_none:""}}{{object.yfcaseStreet|default_if_none:""}}{{object.yfcaseSection|default_if_none:""}}{{object.yfcaseLane|default_if_none:""}}{{object.yfcaseAlley|default_if_none:""}}{{object.yfcaseNumber|default_if_none:""}}{{object.yfcaseFloor|default_if_none:""}}
    </td>
  </tr>
</table>

templates/yfcase/partials/build.html
<!-- 建物 -->
{% load urlify %}
<table class="yfratingscalePDFBuild col">
  <tr>
    <th rowspan="2" style="width:20%">
      建號
    </th>
    <th rowspan="2" style="width:7%">建號<br>謄本</th>
    <th rowspan="2" style="width:15%">建坪(面積)<br>平方公尺(坪)</th>
    <th rowspan="2" style="width:9%">持分</th>  
    <th colspan="2">建坪持分 - 平方公尺(坪)</th>
    <th rowspan="2" style="width:23%">
      <div style="font-size:10.5pt;color;red;background-color:Cornsilk;text-align:center;">
       使用分區：{{ object.builds.first.buildUsePartition|default_if_none:"" }}
      </div>
      建物型/使用
    </th>
  </tr>
  <tr>
    <th>(原)</th>
    <th>(計算後)</th>
  </tr>
  {% for build in object.builds.all %}
    <tr>
      <td style="text-align:left; ">
        <div style="font-size:12pt;">
           {% if request.user.userFullName == object.get_user_username or request.user.userFullName == "管理者" %}
         <span style="font-size: 10pt;vertical-align: middle;">
            <a href="javascript:void(0)" onclick="build_modal_edit('{% url 'yfcase:build_edit' build.id %}')">
              <span class="fa-stack" style="color:DarkGreen;">
                <i class="far fa-circle fa-stack-2x" ></i>
                <i class="fas fa-pen fa-stack-1x"></i>
              </span>
            </a>
            <a href="javascript:void(0)" onclick="build_modal_delete('{% url 'yfcase:build_delete' build.id %}')">
                <span class="fa-stack" style="color:DarkRed;">
                  <i class="far fa-circle fa-stack-2x" ></i>
                  <i class="fas fa-trash fa-stack-1x"></i>
                </span>
              </a>
          </span>
          {% endif %}
        {{object.yfcaseBigSection|default_if_none:""}}{{ build.buildNumber }}
        </div>
      </td>
      <td>
        {% if build.buildUrl != None %}
          <a href="{{ build.buildUrl }}" target="_blank">
            <span style="font-size: 20pt;">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-paperclip" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z"/>
              </svg>
            </span>
          </a>
        {% endif %}
      </td>
      <td>
        {% if build.buildArea != 0 %}
          {{ build.buildArea }} m<sup>2</sup><br> 
          ({{ build.buildArea|m2toping|floatformat:"2" }} 坪) 
        {% endif %}
      </td>
      <td>
        {% if build.buildHoldingPointPersonal > 0 and build.buildHoldingPointAll > 0 %}
          <div style="margin: 0px 10px;">{{ build.buildHoldingPointPersonal }}</div>
          <div style="border-top: 1px solid black;width:auto; display:inline-block !important; display:inline;padding:0px 10px;">{{ build.buildHoldingPointAll }}</div>
        {% endif %}
      </td>
      <td>
        {% if build.buildHoldingPointPersonal > 0 and build.buildHoldingPointAll > 0 %}
          {{ build.get_build_holding_point_area|floatformat:"2" }} m<sup>2</sup><br> 
          ({{ build.get_build_holding_point_area|m2toping|floatformat:"2" }} 坪) 
        {% endif %}
      </td>
      <td>
        {% if build.buildTypeUse == "公設" %}
          {{ build.get_build_first_not_add_and_not_public_holding_point_area|floatformat:"2" }} m<sup>2</sup><br> 
          ({{ build.get_build_first_not_add_and_not_public_holding_point_area|m2toping|floatformat:"2" }} 坪)
        {% elif build.buildTypeUse == "增建-持分後坪數打對折" %}
          {{ build.get_after_add_holding_point_area|floatformat:"2" }} m<sup>2</sup><br> 
          ({{ build.get_after_add_holding_point_area|m2toping|floatformat:"2" }} 坪)
        {% else %}
          {{ build.get_build_holding_point_area|floatformat:"2" }} m<sup>2</sup><br> 
          ({{ build.get_build_holding_point_area|m2toping|floatformat:"2" }} 坪)
        {% endif %}
      </td>
      <td>
        {{ build.buildTypeUse|default_if_none:"" }}
      </td>
    </tr>
  {% endfor %}
</table>

templates/yfcase/partials/build_clicklist.html
<table class="yfratingscalePDFBuildCheckList col">
  <tr>
    <th style="height: 40px;">
      查檢項目
    </th>
  </tr>
  <tr>
    <td style="height: 200px;">
      {% if object.clicklists.first.clicklistOccupy %} 01.占用鄰地<br> {% endif %}
      {% if object.clicklists.first.clicklistEegister %} 02.無未保存登記建物<br> {% endif %}
      {% if object.clicklists.first.clicklistParkingSpace %} 03.附停車位(機車/汽車)<br> {% endif %}
      {% if object.clicklists.first.clicklistManagementFee %} 04.積欠管理費<br> {% endif %}
      {% if object.clicklists.first.clicklistRent %} 05.出租/出借/佔用<br> {% endif %}
      {% if object.clicklists.first.clicklistLeak %} 06.無嚴重漏水現象<br> {% endif %}
      {% if object.clicklists.first.clicklistEasyParking %} 07.停車方便<br> {% endif %}
      {% if object.clicklists.first.clicklistRailway %} 08.鄰近捷運站/台鐵站<br> {% endif %}
      {% if object.clicklists.first.clicklistVegetableMarket %} 09.鄰近菜市場<br> {% endif %}
      {% if object.clicklists.first.clicklistSupermarket %} 10.鄰近大賣場<br> {% endif %}
      {% if object.clicklists.first.clicklistSchool %} 11.鄰近學校<br> {% endif %}
      {% if object.clicklists.first.clicklistPark %} 12.鄰近公園<br> {% endif %}
      {% if object.clicklists.first.clicklistPostOffice %} 13.鄰近郵局/機關<br> {% endif %}
      {% if object.clicklists.first.clicklistMainRoad %} 14.鄰近幹道<br> {% endif %}
      {% if object.clicklists.first.clicklistWaterAndPowerFailure %} 15.斷水斷電<br>   {% endif %}
      {% if object.clicklists.first.clicklistGoodVision %} 16.採光視野良好<br> {% endif %}
    </td> 
  </tr>
</table>

templates/yfcase/partials/finalDecision.html
<!-- 最終判定 -->
<table class="yfratingscalePDFFinaldecision col">
  <tr>
    <th style="width:40%;height: 65px;">
      結論<br>
      <small style="color:red;"><b>※結論判定日需為五天前</b></small>
    </th>
    <th style="width:25%;">
      區域負責人
    </th>
    <td>
      <div style="border:3px solid red;margin:4px;border-radius: 10px;color:red;width:auto; display:inline-block !important; display:inline;padding:0px 20px;">
        <h4 style="margin: 0px;">{{ object.regionalHead|default_if_none:"" }}</h4>
        <h6 style="margin: 0px;">{{ object.regionalHeadDate|default_if_none:"" }}</h6>
        <h4 style="margin: 0px;">{{ object.regionalHeadWorkArea|default_if_none:"" }}</h4>
      </div>
    </td>
  </tr>
  <tr>
    <td rowspan="2">
      {% if object.finalDecision == "1拍進場" %}
        <div class="yfratingscalePDFFinaldecisionJudgment" style="color:brown;border:5px solid brown;width:auto; display:inline-block !important; display:inline;">
          {{ object.finalDecision }}
        </div>
      {% elif object.finalDecision == "2拍進場" %}
        <div class="yfratingscalePDFFinaldecisionJudgment" style="color:purple;border:5px solid purple;width:auto; display:inline-block !important; display:inline;">
          {{ object.finalDecision }}
        </div>
      {% elif object.finalDecision == "3拍進場" %}
        <div class="yfratingscalePDFFinaldecisionJudgment" style="color:blue;border:5px solid blue;width:auto; display:inline-block !important; display:inline;">
          {{ object.finalDecision }}
        </div>
      {% elif object.finalDecision == "4拍進場" %}
        <div class="yfratingscalePDFFinaldecisionJudgment" style="color:green;border:5px solid green;width:auto; display:inline-block !important; display:inline;">
          {{ object.finalDecision }}
        </div>
      {% elif object.finalDecision == "放棄" %}
        <div class="yfratingscalePDFFinaldecisionJudgment" style="color:red;border:5px solid red;width:auto; display:inline-block !important; display:inline;">
          {{ object.finalDecision }}
        </div>
      {% endif %}
    </td>

    <!-- 副署人員1 -->
    <!-- 編輯：副署人員1需為空格，且登入者不可為區域負責人、副署人員2 -->
    <!-- 刪除：副署人員1不可空格，且登入者需為區域負責人或是管理者 -->
    <th style="width:18%;height: 65px;">
      <div style="font-size:12pt;">
        <span style="font-size: 10pt;vertical-align: middle;">
          {% if object.subSigntrueA == None %}
            {% if request.user.userFullName != object.subSigntrueB and request.user.userFullName != object.regionalHead %}
              <a href="javascript:void(0)" onclick="subsigntruea_modal_edit('{% url 'yfcase:subsigntruea_edit' yfcase.id %}')">
                <span class="fa-stack" style="color:DarkGreen;">
                  <i class="far fa-circle fa-stack-2x" ></i>
                  <i class="fas fa-pen fa-stack-1x"></i>
                </span>
              </a>
            {% endif %}
          {% else %}
            {% if request.user.userFullName == "管理者" or request.user.userFullName == object.regionalHead %}
              <a href="javascript:void(0)" onclick="subsigntruea_modal_delete('{% url 'yfcase:subsigntruea_delete' yfcase.id %}')">
                <span class="fa-stack" style="color:DarkRed;">
                  <i class="far fa-circle fa-stack-2x" ></i>
                  <i class="fas fa-trash fa-stack-1x"></i>
                </span>
              </a>
            {% endif %}
          {% endif %}
        </span>
      </div>
      副署人員1
    </th>
    <td>
      {% if object.subSigntrueA %}
        <div style="border:3px solid red;margin:4px;border-radius: 10px;color:red;width:auto; display:inline-block !important; display:inline;padding:0px 20px;">
          <h4 style="margin: 0px;">{{ object.subSigntrueA|default_if_none:"" }}</h4>
          <h6 style="margin: 0px;">{{ object.subSigntrueDateA|default_if_none:"" }}</h6>
          <h4 style="margin: 0px;">{{ object.subSigntrueWorkAreaA|default_if_none:"" }}</h4>
        </div>
      {% endif %}
    </td>
  </tr>

  <!-- 副署人員2 -->
  <!-- 編輯：對應拍數的拍賣金額需大於1000000，且副署人員2需為空格，且登入者不可為區域負責人、副署人員1 -->
  <!-- 刪除：副署人員2不可空格，且登入者需為區域負責人或是管理者 -->
  <tr>
    <th style="width:18%;height: 65px;">

        <div style="font-size:12pt;">
          <span style="font-size: 10pt;vertical-align: middle;">
            {% if object.get_floor_price_from_auction_date >= 1000000 %}
              {% if object.subSigntrueB == None %}
                {% if request.user.userFullName != object.subSigntrueA and request.user.userFullName != object.regionalHead %}
                  <a href="javascript:void(0)" onclick="subsigntrueb_modal_edit('{% url 'yfcase:subsigntrueb_edit' object.id %}')">
                    <span class="fa-stack" style="color:DarkGreen;">
                      <i class="far fa-circle fa-stack-2x" ></i>
                      <i class="fas fa-pen fa-stack-1x"></i>
                    </span>
                  </a>
                {% endif %}
              {% else %}
                {% if request.user.userFullName == "管理者" or request.user.userFullName == object.regionalHead %}
                  <a href="javascript:void(0)" onclick="subsigntrueb_modal_delete('{% url 'yfcase:subsigntrueb_delete' object.id %}')">
                    <span class="fa-stack" style="color:DarkRed;">
                      <i class="far fa-circle fa-stack-2x" ></i>
                      <i class="fas fa-trash fa-stack-1x"></i>
                    </span>
                  </a>
                {% endif %}
              {% endif %}
            {% else %}
              <div style="color:green;border:3px solid blue;border-radius: 10px;width:auto; display:inline-block !important; display:inline;color:blue;padding:0px 20px;">最近一拍底價 < 1000000</div>
            {% endif %}
          </span>
        </div>

      副署人員2
    </th>
    <td>
      {% if object.subSigntrueB %}
        <div style="border:3px solid red;margin:4px;border-radius: 10px;color:red;width:auto; display:inline-block !important; display:inline;padding:0px 20px;">
          <h4 style="margin: 0px;">{{ object.subSigntrueB|default_if_none:"" }}</h4>
          <h6 style="margin: 0px;">{{ object.subSigntrueDateB|default_if_none:"" }}</h6>
          <h4 style="margin: 0px;">{{ object.subSigntrueWorkAreaB|default_if_none:"" }}</h4>
        </div>
      {% endif %}
    </td>
  </tr>
</table>

templates/yfcase/partials/land.html
<!-- 土地 -->
{% load urlify %}

<div class="container col">
  <div class="row">
      <table class="yfratingscalePDFLand col">
        <tr>
          <th style="width:20%;">地號</th>
          <th style="width:7%;">地號<br>謄本</th>
          <th style="width:15%;">地坪(面積)<br>平方公尺(坪)</th>
          <th style="width:9%;">持分</th>
          <th style="width:15%;">地坪(持分)<br>平方公尺(坪)</th>
        </tr>
        {% for land in object.lands.all %}
          <tr>
            <td style="text-align:left; ">
              {% if request.user.userFullName == object.get_user_username or request.user.userFullName == "管理者" %}
              <div style="font-size:12pt;">
                <span style="font-size: 10pt;vertical-align: middle;">
                  <a href="javascript:void(0)" onclick="land_modal_edit('{% url 'yfcase:land_edit' land.id %}')">
                    <span class="fa-stack" style="color:DarkGreen;">
                      <i class="far fa-circle fa-stack-2x" ></i>
                      <i class="fas fa-pen fa-stack-1x"></i>
                    </span>
                  </a>
                  <a href="javascript:void(0)" onclick="land_modal_delete('{% url 'yfcase:land_delete' land.id %}')">
                    <span class="fa-stack" style="color:DarkRed;">
                      <i class="far fa-circle fa-stack-2x" ></i>
                      <i class="fas fa-trash fa-stack-1x"></i>
                    </span>
                  </a>
                </span>
                {% endif %}
                {{object.yfcaseBigSection|default_if_none:""}}{{ land.landNumber }}
              </div>
            </td>
            <td>
              {% if land.landUrl != None %}
                <a href="{{ land.landUrl }}" target="_blank">
                  <span style="font-size: 20pt;">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-paperclip" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z"/>
                    </svg>
                  </span>
                </a>
              {% endif %}
            </td>
            <td>
              {% if land.landArea != 0 %}
                {{ land.landArea }} m<sup>2</sup><br> 
                ({{ land.landArea|m2toping|floatformat:"2" }} 坪)
              {% endif %}
            </td>
            <td>
              {% if land.landHoldingPointPersonal > 0 and land.landHoldingPointAll > 0 %}
                <div style="margin: 0px 10px;">{{ land.landHoldingPointPersonal }}</div>
                <div style="border-top: 1px solid black;width:auto; display:inline-block !important; display:inline;padding:0px 10px;">{{ land.landHoldingPointAll }}</div>
              {% endif %}
            </td>
            <td>
              {% if land.landHoldingPointPersonal > 0 and land.landHoldingPointAll > 0 %}
                {{ land.get_land_holding_point_area|floatformat:"2" }} m<sup>2</sup><br> 
                ({{ land.get_land_holding_point_area|m2toping|floatformat:"2" }} 坪)
              {% endif %}
            </td>
          </tr>
        {% endfor %}
        
      </table>

  </div>
</div>

templates/yfcase/partials/survey.html
<table class="yfratingscalePDFAttachment col">
  <tr>
    <th style="width:45%">
      初勘日
    </th>
    <td class="yfratingscalePDFAttachmentContent">
      {% for survey in object.surveys.all %}
        {{survey.surveyFirstDay}}
      {% endfor %}
    </td>
  </tr>
  <tr>
    <th>會勘日</th>
    <td class="yfratingscalePDFAttachmentContent">
      {% for survey in object.surveys.all %}
        {{survey.surveySecondDay}}
      {% endfor %}
    </td>
  </tr>
  <tr>
    <th>法拍公告<small>(證物三)</small></th>
    <td class="yfratingscalePDFAttachmentContent">
      {% for survey in object.surveys.all %}
        {% if survey.surveyForeclosureAnnouncementLink %}
          <a href="{{survey.surveyForeclosureAnnouncementLink}}" target="_blank">法拍公告</a>
        {% endif %}
      {% endfor %}
    </td>
  </tr>
  <tr>
    <th>998連結</th>
    <td class="yfratingscalePDFAttachmentContent">
      {% for survey in object.surveys.all %}
        {% if survey.survey988Link %}
          <a href="{{survey.survey988Link}}" target="_blank">998連結</a>
        {% endif %}
      {% endfor %}
    </td>
  </tr>
  <tr>
    <th>物件照片<small>(證物四)</small></th>
    <td class="yfratingscalePDFAttachmentContent">
      {% for survey in object.surveys.all %}
        {% if survey.surveyObjectPhotoLink %}
          <a href="{{object.surveys.surveyObjectPhotoLink}}" target="_blank">物件照片</a>
        {% endif %}
      {% endfor %}
    </td>
  </tr>
  <tr>
    <th>法拍記錄<small>(證物七)</small></th>
    <td class="yfratingscalePDFAttachmentContent">
      {% for survey in object.surveys.all %}
        {% if survey.surveyForeclosureRecordLink %}
          <a href="{{survey.surveyForeclosureRecordLink}}" target="_blank">法拍記錄</a>
        {% endif %}
      {% endfor %}
    </td>
  </tr>
</table>