src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
  path('', include('yfcases.urls')),
  path('admin/', admin.site.urls),
  path('users/', include('users.urls')),
	path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yfcases/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from wkhtmltopdf.views import PDFTemplateView

app_name='yfcase'

urlpatterns = [
  path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
  path('',views.YfcaseListView.as_view(),name="home" ),
  path('yfcase/<int:pk>/',views.YfcaseDetailView.as_view(),name="yfcase_detail"),
  path('yfcase/new/',views.YfcaseCreateView.as_view(),name="yfcase_new"),
  path('yfcase/<int:pk>/edit/',views.YfcaseUpdateView.as_view(),name="yfcase_edit"),
  path('yfcase/<int:pk>/delete/',views.YfcaseDeleteView.as_view(),name="yfcase_delete"),
  path('land/new/',views.LandCreateView.as_view(),name="land_new"),
  path('land/<int:pk>/edit/',views.LandUpdateView.as_view(),name="land_edit"),
  path('land/<int:pk>/delete/',views.LandDeleteView.as_view(),name="land_delete"),
  path('build/new/',views.BuildCreateView.as_view(),name="build_new"),
  path('build/<int:pk>/edit/',views.BuildUpdateView.as_view(),name="build_edit"),
  path('build/<int:pk>/delete/',views.BuildDeleteView.as_view(),name="build_delete"),
  path('auction/new/',views.AuctionCreateView.as_view(),name="auction_new"),
  path('auction/<int:pk>/edit/',views.AuctionUpdateView.as_view(),name="auction_edit"),
  path('survey/new/',views.SurveyCreateView.as_view(),name="survey_new" ),
  path('survey/<int:pk>/edit/',views.SurveyUpdateView.as_view(),name="survey_edit" ),
  path('clicklist/new/',views.ClickListCreateView.as_view(),name="clicklist_new" ),
  path('clicklist/<int:pk>/edit/',views.ClickListUpdateView.as_view(),name="clicklist_edit"),
  path('objectbuild/new/',views.ObjectBuildCreateView.as_view(),name="objectbuild_new" ),
  path('objectbuild/<int:pk>/edit/',views.ObjectBuildUpdateView.as_view(),name="objectbuild_edit"),
  path('objectbuild/<int:pk>/delete/',views.ObjectBuildDeleteView.as_view(),name="objectbuild_delete"),
  path('scorea/<int:pk>/edit/',views.ScoreAUpdateView.as_view(),name="score_a_edit"),
  path('scoreb/<int:pk>/edit/',views.ScoreBUpdateView.as_view(),name="score_b_edit"),
  path('scorec/<int:pk>/edit/',views.ScoreCUpdateView.as_view(),name="score_c_edit"),
  path('scorea/<int:pk>/delete/',views.ScoreADeleteView.as_view(),name="score_a_delete"),
  path('scoreb/<int:pk>/delete/',views.ScoreBDeleteView.as_view(),name="score_b_delete"),
  path('scorec/<int:pk>/delete/',views.ScoreCDeleteView.as_view(),name="score_c_delete"),
  path('regionalhead/new/',views.RegionalHeadCreateView.as_view(),name="regionalhead_new" ),
  path('regionalhead/<int:pk>/edit/',views.RegionalHeadUpdateView.as_view(),name="regionalhead_edit" ),
  path('regionalhead/<int:pk>/delete/',views.RegionalHeadDeleteView.as_view(),name="regionalhead_delete" ),
  path('subsigntruea/new/',views.SubSigntrueACreateView.as_view(),name="subsigntruea_new" ),
  path('subsigntruea/<int:pk>/edit/',views.SubSigntrueAUpdateView.as_view(),name="subsigntruea_edit" ),
  path('subsigntruea/<int:pk>/delete/',views.SubSigntrueADeleteView.as_view(),name="subsigntruea_delete" ),
  path('subsigntrueb/new/',views.SubSigntrueBCreateView.as_view(),name="subsigntrueb_new" ),
  path('subsigntrueb/<int:pk>/edit/',views.SubSigntrueBUpdateView.as_view(),name="subsigntrueb_edit" ),
  path('subsigntrueb/<int:pk>/delete/',views.SubSigntrueBDeleteView.as_view(),name="subsigntrueb_delete" ),
  path('ajax/load-townships/', views.load_townships, name='ajax_load_townships'),
  
  path('deedtax/<int:pk>/edit/', views.DeedtaxUpdateView.as_view(), name='deedtax_edit'),
  path('realestateregistration/<int:pk>/edit/', views.RealestateregistrationUpdateView.as_view(), name='realestateregistration_edit'),
  path('complaint/<int:pk>/edit/', views.ComplaintUpdateView.as_view(), name='complaint_edit'),
  path('letter/<int:pk>/edit/', views.LetterUpdateView.as_view(), name='letter_edit'),
  path('commonpropertydivision/<int:pk>/edit/', views.CommonpropertydivisionUpdateView.as_view(), name='commonpropertydivision_edit'),
  
  path('yfratingscalePDFView/<int:pk>/', views.yfratingscalePDFView.as_view(),name="yfratingscalePDF_View"),
  path('deedtaxPDFView/<int:pk>/', views.deedtaxPDFView.as_view(),name="deedtaxPDF_View"),
  path('realestateregistrationPDFView/<int:pk>/', views.realestateregistrationPDFView.as_view(),name="realestateregistrationPDF_View"),
  path('complaintPDFView/<int:pk>/', views.complaintPDFView.as_view(),name="complaintPDF_View"),
  path('letterPDFView/<int:pk>/', views.letterPDFView.as_view(),name="letterPDF_View"),
  path('commonpropertydivisionPDFView/<int:pk>/', views.commonpropertydivisionPDFView.as_view(),name="commonpropertydivisionPDF_View"),
]

templates/score/score_a_delete.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:score_a_delete' objectbuild.id %}" method="post">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">刪除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
        <p>你確定要刪除勘查者 "{{objectbuild.objectBuildScorerA}}" 的評比 ?</p>
        {{ form.objectBuildScorerA|attr:"type:hidden" }}
        {{ form.objectBuildScorRateA|attr:"type:hidden" }}
        {{ form.objectBuildScorReasonA|attr:"type:hidden" }}
        {{ form.plusItemA1|attr:"type:hidden" }}
        {{ form.plusItemA2|attr:"type:hidden" }}
        {{ form.plusItemA3|attr:"type:hidden" }}
        {{ form.plusItemA4|attr:"type:hidden" }}
        {{ form.plusItemA5|attr:"type:hidden" }}
        {{ form.plusItemOtherA|attr:"type:hidden" }}
        {{ form.plusValueA1|attr:"type:hidden" }}
        {{ form.plusValueA2|attr:"type:hidden" }}
        {{ form.plusValueA3|attr:"type:hidden" }}
        {{ form.plusValueA4|attr:"type:hidden" }}
        {{ form.plusValueA5|attr:"type:hidden" }}
        {{ form.plusValueOtherA|attr:"type:hidden" }}
      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
        <input class="btn btn-success col-md-3" type="submit" onclick="set_value_empty()" value="刪除" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  function set_value_empty() {
   $(function() {
     document.getElementById("id_objectBuildScorerA").value = "";
     document.getElementById("id_objectBuildScorRateA").value = 0;
     document.getElementById("id_objectBuildScorReasonA").value = "";
     document.getElementById("id_plusItemA1").value = "";
     document.getElementById("id_plusItemA2").value = "";
     document.getElementById("id_plusItemA3").value = "";
     document.getElementById("id_plusItemA4").value = "";
     document.getElementById("id_plusItemA5").value = "";
     document.getElementById("id_plusItemOtherA").value = "";
     document.getElementById("id_plusValueA1").value = 0;
     document.getElementById("id_plusValueA2").value = 0;
     document.getElementById("id_plusValueA3").value = 0;
     document.getElementById("id_plusValueA4").value = 0;
     document.getElementById("id_plusValueA5").value = 0;
     document.getElementById("id_plusValueOtherA").value = 0;
    });
  }
</script>
{% endblock javascript %}

templates/score/score_a_edit.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:score_a_edit' objectbuild.id %}" method="post">{% csrf_token %}

  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}-評比人員：{{ user.fullname }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
        {{ form.objectBuildScorerA|attr:"type:hidden" }}
        {{ form.objectBuildScorRateA|attr:"type:hidden" }}
        {{ form.objectBuildScorReasonA|attr:"type:hidden" }}

        <div class="form-row">
          <div class="form-group col-md-1">
            <label>項目1</label>
          </div>
          <div class="form-group col-md-7">
            {{ form.plusItemA1|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-2">
            {{ form.plusValueA1|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-1">
            <label>項目2</label>
          </div>
          <div class="form-group col-md-7">
            {{ form.plusItemA2|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-2">
            {{ form.plusValueA2|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-1">
            <label>項目3</label>
          </div>
          <div class="form-group col-md-7">
            {{ form.plusItemA3|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-2">
            {{ form.plusValueA3|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-1">
            <label>項目4</label>
          </div>
          <div class="form-group col-md-7">
            {{ form.plusItemA4|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-2">
            {{ form.plusValueA4|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-1">
            <label>項目5</label>
          </div>
          <div class="form-group col-md-7">
            {{ form.plusItemA5|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-2">
            {{ form.plusValueA5|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>
        
        <hr>

        <div class="form-row">
          <div class="form-group col-md-1">
            <label>其他</label>
          </div>
          <div class="form-group col-md-7">
            {{ form.plusItemOtherA|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-2">
            {{ form.plusValueOtherA|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>
        {{ request.user.userFullName|json_script:"author_fullname" }}
        
      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary col" data-dismiss="modal">返回</button>
        <input class="btn btn-primary col-md-3" type="submit" onclick="post_score_a_edit_submit()" value="加入評比" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  function post_score_a_edit_submit() {
    const author_fullname = JSON.parse(document.getElementById('author_fullname').textContent);
    document.getElementById("id_objectBuildScorerA").value = author_fullname;
  }
</script>
{% endblock javascript %}

templates/score/score_b_delete.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:score_b_delete' objectbuild.id %}" method="post">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">刪除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
        <p>你確定要刪除勘查者 "{{objectbuild.objectBuildScorerB}}" 的評比 ?</p>
        {{ form.objectBuildScorerB|attr:"type:hidden" }}
        {{ form.objectBuildScorRateB|attr:"type:hidden" }}
        {{ form.objectBuildScorReasonB|attr:"type:hidden" }}
        {{ form.plusItemB1|attr:"type:hidden" }}
        {{ form.plusItemB2|attr:"type:hidden" }}
        {{ form.plusItemB3|attr:"type:hidden" }}
        {{ form.plusItemB4|attr:"type:hidden" }}
        {{ form.plusItemB5|attr:"type:hidden" }}
        {{ form.plusItemOtherB|attr:"type:hidden" }}
        {{ form.plusValueB1|attr:"type:hidden" }}
        {{ form.plusValueB2|attr:"type:hidden" }}
        {{ form.plusValueB3|attr:"type:hidden" }}
        {{ form.plusValueB4|attr:"type:hidden" }}
        {{ form.plusValueB5|attr:"type:hidden" }}
        {{ form.plusValueOtherB|attr:"type:hidden" }}
      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
        <input class="btn btn-success col-md-3" type="submit" onclick="set_value_empty()" value="刪除" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  function set_value_empty() {
   $(function() {
     document.getElementById("id_objectBuildScorerB").value = "";
     document.getElementById("id_objectBuildScorRateB").value = 0;
     document.getElementById("id_objectBuildScorReasonB").value = "";
     document.getElementById("id_plusItemB1").value = "";
     document.getElementById("id_plusItemB2").value = "";
     document.getElementById("id_plusItemB3").value = "";
     document.getElementById("id_plusItemB4").value = "";
     document.getElementById("id_plusItemB5").value = "";
     document.getElementById("id_plusItemOtherB").value = "";
     document.getElementById("id_plusValueB1").value = 0;
     document.getElementById("id_plusValueB2").value = 0;
     document.getElementById("id_plusValueB3").value = 0;
     document.getElementById("id_plusValueB4").value = 0;
     document.getElementById("id_plusValueB5").value = 0;
     document.getElementById("id_plusValueOtherB").value = 0;
    });
  }
</script>
{% endblock javascript %}

templates/score/score_b_edit.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:score_b_edit' objectbuild.id %}" method="post">{% csrf_token %}

  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}-評比人員：{{ user.fullname }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
       
        {{ form.objectBuildScorerB|attr:"type:hidden" }}
        {{ form.objectBuildScorRateB|attr:"type:hidden" }}
        {{ form.objectBuildScorReasonB|attr:"type:hidden" }}

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目1</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemB1|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueB1|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目2</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemB2|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueB2|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目3</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemB3|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueB3|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目4</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemB4|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueB4|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目5</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemB5|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueB5|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>其他</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemOtherB|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueOtherB|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>
        {{ request.user.userFullName|json_script:"author_fullname" }}

      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary col" data-dismiss="modal">返回</button>
        <input class="btn btn-primary col-md-3" type="submit" onclick="post_score_b_edit_submit()" value="加入評比" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  function post_score_b_edit_submit() {
    const author_fullname = JSON.parse(document.getElementById('author_fullname').textContent);
    document.getElementById("id_objectBuildScorerB").value = author_fullname;
  }
</script>
{% endblock javascript %}

templates/score/score_c_delete.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:score_c_delete' objectbuild.id %}" method="post">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">刪除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
        <p>你確定要刪除勘查者 "{{objectbuild.objectBuildScorerC}}" 的評比 ?</p>
        {{ form.objectBuildScorerC|attr:"type:hidden" }}
        {{ form.objectBuildScorRateC|attr:"type:hidden" }}
        {{ form.objectBuildScorReasonC|attr:"type:hidden" }}
        {{ form.plusItemC1|attr:"type:hidden" }}
        {{ form.plusItemC2|attr:"type:hidden" }}
        {{ form.plusItemC3|attr:"type:hidden" }}
        {{ form.plusItemC4|attr:"type:hidden" }}
        {{ form.plusItemC5|attr:"type:hidden" }}
        {{ form.plusItemOtherC|attr:"type:hidden" }}
        {{ form.plusValueC1|attr:"type:hidden" }}
        {{ form.plusValueC2|attr:"type:hidden" }}
        {{ form.plusValueC3|attr:"type:hidden" }}
        {{ form.plusValueC4|attr:"type:hidden" }}
        {{ form.plusValueC5|attr:"type:hidden" }}
        {{ form.plusValueOtherC|attr:"type:hidden" }}
      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
        <input class="btn btn-success col-md-3" type="submit" onclick="set_value_empty()" value="刪除" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  function set_value_empty() {
   $(function() {
     document.getElementById("id_objectBuildScorerC").value = "";
     document.getElementById("id_objectBuildScorRateC").value = 0;
     document.getElementById("id_objectBuildScorReasonC").value = "";
     document.getElementById("id_plusItemC1").value = "";
     document.getElementById("id_plusItemC2").value = "";
     document.getElementById("id_plusItemC3").value = "";
     document.getElementById("id_plusItemC4").value = "";
     document.getElementById("id_plusItemC5").value = "";
     document.getElementById("id_plusItemOtherC").value = "";
     document.getElementById("id_plusValueC1").value = 0;
     document.getElementById("id_plusValueC2").value = 0;
     document.getElementById("id_plusValueC3").value = 0;
     document.getElementById("id_plusValueC4").value = 0;
     document.getElementById("id_plusValueC5").value = 0;
     document.getElementById("id_plusValueOtherC").value = 0;
    });
  }
</script>
{% endblock javascript %}

templates/score/score_c_edit.html
{% load widget_tweaks %}
<form action="{% url 'yfcase:score_c_edit' objectbuild.id %}" method="post">{% csrf_token %}

  <div class="modal-dialog">
    <div class="modal-content">

      <!-- header -->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{title}}-評比人員：{{ user.fullname }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- body -->
      <div class="modal-body">
       
        {{ form.objectBuildScorerC|attr:"type:hidden" }}
        {{ form.objectBuildScorRateC|attr:"type:hidden" }}
        {{ form.objectBuildScorReasonC|attr:"type:hidden" }}
        
        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目1</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemC1|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueC1|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目2</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemC2|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueC2|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目3</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemC3|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueC3|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目4</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemC4|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueC4|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>項目5</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemC5|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueC5|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-2">
            <label>其他</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusItemOtherC|add_class:"form-control fieldcolor pt-0" }}
          </div>
          <div class="form-group col-md-2">
            <label>加成係數</label>
          </div>
          <div class="form-group col-md-4">
            {{ form.plusValueOtherC|add_class:"form-control fieldcolor pt-0" }}
          </div>
        </div>
        {{ request.user.userFullName|json_script:"author_fullname" }}

      </div>

      <!-- footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary col" data-dismiss="modal">返回</button>
        <input class="btn btn-primary col-md-3" type="submit" onclick="post_score_c_edit_submit()" value="加入評比" />
      </div>

    </div>
  </div>
</form>

{% block javascript %}
<script>
  function post_score_c_edit_submit() {
    const author_fullname = JSON.parse(document.getElementById('author_fullname').textContent);
    document.getElementById("id_objectBuildScorerC").value = author_fullname;
  }
</script>
{% endblock javascript %}