src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
  path('', include('yfcases.urls')),
  path('admin/', admin.site.urls),
  path('users/', include('users.urls')),
	path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
  userFirstName=models.CharField(u'姓氏',max_length=50,null=True,blank=True)
  userLastName=models.CharField(u'名字',max_length=50,null=True,blank=True)
  userFullName=models.CharField(u'全名',max_length=50,null=True,blank=True)
  userWorkArea=models.CharField(u'工作轄區',max_length=50,null=True,blank=True)
  userRole=models.PositiveIntegerField(u'權限',default=0)
  userIdentityCard=models.CharField(u'身分証號',max_length=50,null=True,blank=True)
  userBirthday=models.DateField(u'生日',null=True,blank=True)
  userLocalPhone=models.CharField(u'市話',max_length=50,null=True,blank=True)
  userMobilePhone=models.CharField(u'手機',max_length=50,null=True,blank=True)
  userCountry=models.CharField(u'縣市',max_length=50,null=True,blank=True)
  userTownship=models.CharField(u'鄉鎮',max_length=50,null=True,blank=True)
  userVillage=models.CharField(u'村里',max_length=50,null=True,blank=True)
  userNeighbor=models.CharField(u'鄰',max_length=50,null=True,blank=True)
  userStreet=models.CharField(u'街路',max_length=50,null=True,blank=True)
  userSection=models.CharField(u'段',max_length=50,null=True,blank=True)
  userLane=models.CharField(u'巷',max_length=50,null=True,blank=True)
  userAlley=models.CharField(u'弄',max_length=50,null=True,blank=True)
  userNumber=models.CharField(u'號',max_length=50,null=True,blank=True)
  userFloor=models.CharField(u'樓',max_length=50,null=True,blank=True)
  userPublicOrPrivate=models.CharField(u'身分別',max_length=50,null=True,blank=True)
  
  def __str__(self):
    # 要寫成str(self.userFullName)要不然在/admin執行時會出現"__str__ returned non-string (type NoneType)"
    return str(self.userFullName)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@500&display=swap" rel="stylesheet">
  <title>
    {% block head_title %}
    {% endblock head_title %}
  </title>
    <!-- Bootstrap V4.3.1 CSS部份 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Bootstrap Validator V0.5.2 CSS部份 -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.2/css/bootstrapValidator.min.css"/>
    <!-- JQuery UI CSS for datepicker用 -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- 自訂的部份 -->
    <!-- <link rel="stylesheet" href="{% static 'css/base.css' %}" /> -->
    {% block style %}
    {% endblock style %}
</head>
<body>
  {% include 'partials/navbar.html' %}
  {% include "messages_display.html" %}
  <div class="container-fluid">
    {% block content %}
    {% endblock content %}
  </div>
  
  <!-- Bootstrap V4.5.3 JS部份 -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <!-- Font Awesome new JS部份 -->
  <script src="https://kit.fontawesome.com/6cbc1ff495.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-modal/2.2.6/js/bootstrap-modalmanager.min.js" integrity="sha512-/HL24m2nmyI2+ccX+dSHphAHqLw60Oj5sK8jf59VWtFWZi9vx7jzoxbZmcBeeTeCUc7z1mTs3LfyXGuBU32t+w==" crossorigin="anonymous"></script>
  <!-- JQuery UI JS for datepicker用 -->
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <!-- Bootstrap Validator V0.5.2 JS部份 -->
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.2/js/bootstrapValidator.min.js"></script>
  {% block javascript %}
	{% endblock %}
</body>
</html>

templates/messages_display.html
{% if messages %}
<ul class="messages">
  {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
      {{ message }}
    </li>
  {% endfor %}
</ul>

{% endif %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title %}Sign Up{% endblock %}



{% block content %}
<style type="text/css">
  .baserow {
    padding-bottom:10px;
  }
</style>

	<h2>註冊新會員</h2>
	<form method="post">
		{% csrf_token %}
		
		<div class="accordion" id="accordionExample">
      <div class="card">
        <div class="card-header bg-success" id="headingOne" style="padding:0px;">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left text-white" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              <i class="fas fa-notes-medical"></i> 基本資料(必填)
            </button>
          </h2>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
          <div class="card-body">
            <div class="row">
              <div class="col-md-6" style="background-color:BurlyWood;">
                
                <div class="baserow">
             
                  <label for="id_username">姓名(英文-登入用)</label>
                  <input type="text" name="username"  autocapitalize="none" autocomplete="username" autofocus required id="id_username" /><br />
                  <span class="helptext">
                    <small style="color:red;">
                      <ul>
                        <li>
                          需要。150個字符以內。僅允許字母、數字和 @/./+/-/_
                        </li>
                      </ul>
                    </small>
                  </span>
                </div>
                
                <div class="baserow">
                  <label for="id_userFullName">姓名(中文全名):</label>
                  <input type="text" name="userFullName" maxlength="50" id="id_userFullName" />
                </div>
                
                <div class="baserow">
                  <label for="id_email">信箱:</label>
                  <input type="email" name="email" maxlength="254" id="id_email" />
                </div>
                
                <div class="baserow">
                  <label for="id_userWorkArea">工作轄區:</label>
                  <input type="text" name="userWorkArea" maxlength="50" id="id_userWorkArea" />
                </div>
                
                <div class="baserow">
                  <label for="id_userRole">權限:</label>
                  <input type="number" name="userRole" value="0" min="0" required id="id_userRole" />
                </div>
                
              </div>
              
              <div class="col-md-6" style="background-color:BlanchedAlmond;">

                <div class="baserow">
                  <label for="id_password1">登入密碼:</label>
                  <input type="password" name="password1" autocomplete="new-password" required id="id_password1" /><br />
                  <span class="helptext">
                    <small style="color:red;">
                      <ul>
                          <li>您的密碼不能與其他個人信息太相似.</li>
                          <li>您的密碼必須至少包含8個字元.</li>
                          <li>您的密碼不能是常用密碼.</li>
                          <li>您的密碼不能全是數字.</li>
                      </ul>
                    </small>
                  </span>
                </div>
                
                <div class="baserow">
                  <label for="id_password2">密碼確認:</label>
                  <input type="password" name="password2" autocomplete="new-password" required id="id_password2" /><br />
                  <span class="helptext">
                    <small style="color:red;">
                      <ul>
                        <li>
                          輸入與登入密碼相同的密碼進行驗證。
                        </li>
                      </ul>
                    </small>
                  </span>
                </div>
                
              </div>
            </div>

          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header bg-info" id="headingTwo" style="padding:0px;">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left collapsed text-white" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              <i class="fas fa-window-restore"></i> 進階資料(選填)
            </button>
          </h2>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
          <div class="card-body">
             <div class="row">
              <div class="col-md-4" style="background-color:LightGrey;">
                <div class="baserow">
                  <label for="id_userIdentityCard">身分証號:</label>
                  <input type="text" name="userIdentityCard" maxlength="50" id="id_userIdentityCard" class="form-control" />
                </div>
                <div class="baserow">
                  <label for="id_userBirthday">生日:</label>
                  <input type="text" name="userBirthday" id="id_userBirthday" class="form-control" />
                </div>
                <div class="baserow">
                  <label for="id_userLocalPhone">市話:</label>
                  <input type="text" name="userLocalPhone" maxlength="50" id="id_userLocalPhone" class="form-control" />
                </div>
                <div class="baserow">
                  <label for="id_userMobilePhone">手機:</label>
                  <input type="text" name="userMobilePhone" maxlength="50" id="id_userMobilePhone" class="form-control" />
                </div>
                <div class="baserow">
                  <label for="id_userPublicOrPrivate">身分別:</label>
                  <input type="text" name="userPublicOrPrivate" maxlength="50" id="id_userPublicOrPrivate" class="form-control" />
                </div>
              </div>
              <div class="col-md-8" style="background-color:LightSteelBlue;">
                <div class="baserow">
                  <div class="row">
                    <div class="col-md-6">
                      <label for="id_userCountry">縣市:</label>
                      <input type="text" name="userCountry" maxlength="50" id="id_userCountry" class="form-control" />
                    </div>
                    <div class="col-md-6">
                      <label for="id_userTownship">鄉鎮:</label>
                      <input type="text" name="userTownship" maxlength="50" id="id_userTownship" class="form-control" />
                    </div>
                  </div>
                </div>
              
                <div class="baserow">
                  <div class="row">
                    <div class="col-md-6">
                      <label for="id_userVillage">村里:</label>
                      <input type="text" name="userVillage" maxlength="50" id="id_userVillage" class="form-control" />
                    </div>
                    <div class="col-md-6">
                      <label for="id_userNeighbor">鄰:</label>
                      <input type="text" name="userNeighbor" maxlength="50" id="id_userNeighbor" class="form-control" />
                    </div>
                  </div>
                </div>
                <div class="baserow">
                  <div class="row">
                    <div class="col-md-6">
                      <label for="id_userStreet">街路:</label>
                      <input type="text" name="userStreet" maxlength="50" id="id_userStreet" class="form-control" />
                    </div>
                    <div class="col-md-6">
                      <label for="id_userSection">段:</label>
                      <input type="text" name="userSection" maxlength="50" id="id_userSection" class="form-control" />
                    </div>
                  </div>
                </div>
                <div class="baserow">
                  <div class="row">
                    <div class="col-md-3">
                      <label for="id_userLane">巷:</label>
                      <input type="text" name="userLane" maxlength="50" id="id_userLane" class="form-control" />
                    </div>
                    <div class="col-md-3">
                      <label for="id_userAlley">弄:</label>
                      <input type="text" name="userAlley" maxlength="50" id="id_userAlley" class="form-control" />
                    </div>
                    <div class="col-md-3">
                      <label for="id_userNumber">號:</label>
                      <input type="text" name="userNumber" maxlength="50" id="id_userNumber" class="form-control" />
                    </div>
                    <div class="col-md-3">
                      <label for="id_userFloor">樓:</label>
                      <input type="text" name="userFloor" maxlength="50" id="id_userFloor" class="form-control" />
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <button class="btn btn-secondary" type="submit">註冊</button>
	</form>
</div>
{% endblock %}